version: '3'
services:
  # Httpd
  raharuapp_httpd:
    build:
      context: ./
      dockerfile: ./httpd/Dockerfile
    env_file: .env
    environment:
      MYSQL_DSN: raharuapp_db
    ports:
      - "80:8080"
    depends_on:
      - raharuapp_db
    volumes:
      - ./data:/var/www/html
  # MySQL
  raharuapp_db:
    image: mysql:5.7
    platform: linux/x86_64
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

# 永続ボリューム
volumes:
  db-data:
