version: '3'
services:
  # Nginx
  raharuapp_web:
    build:
      context: ./
      dockerfile: ./web/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - raharuapp_app
    volumes:
      - ./data:/var/www/html

  # php-fpm-phalocn
  raharuapp_app:
    build:
      context: ./
      dockerfile: ./app/Dockerfile
    env_file: .env
    environment:
      MYSQL_DSN: raharuapp_db
    depends_on:
      - raharuapp_db
    volumes:
      - ./data:/var/www/html
      - ./logs:/var/log/nginx
      - ./app/time_zone.ini:/usr/local/etc/php/conf.d/time_zone.ini

  # MySQL
  raharuapp_db:
    image: mysql:5.7.14
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

# 永続ボリューム
volumes:
  db-data:
