version: '3'
services:
  # Nginx
  rag_web:
    build:
      context: ./
      dockerfile: ./web/Dockerfile
    ports:
      - "86:80"
    depends_on:
      - rag_app
    volumes:
      - ./data:/var/www/html

  # php-fpm-phalocn
  nc_app:
    build:
      context: ./
      dockerfile: ./app/Dockerfile
    env_file: .gce_env
    depends_on:
      - rag_db
    volumes:
      - ./data:/var/www/html
      - ./logs:/var/log/nginx

  # MySQL
  nc_db:
    image: mysql:5.7.14
    env_file: .gce_env
    ports:
      - "3308:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

